# Generated by Django 2.1.7 on 2019-03-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_number',
            field=models.IntegerField(default=1, verbose_name='分类数目'),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_number',
            field=models.IntegerField(default=1, verbose_name='标签数目'),
        ),
    ]
